---
language: java

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - python3
      - python3-pip

before_install:
  - sudo pip3 install --upgrade pip
  - sudo pip3 install vim-vint
  - |
    if [ -z "${GOPATH}" ]; then
      if [ -z "$(go env GOPATH)" ]; then
        export GOPATH="${HOME}"
      else
        export GOPATH="$(go env GOPATH)"
      fi
      export PATH="${GOPATH}/bin:${PATH}"
    fi
  - go get -v github.com/haya14busa/go-vimlparser/cmd/vimlparser

before_script:
  - git clone --depth 1 https://github.com/thinca/vim-themis /tmp/vim-themis
  - git clone --depth 1 https://github.com/thinca/vim-quickrun /tmp/vim-quickrun

script:
  - vim --version
  - /tmp/vim-themis/bin/themis --version
  - /tmp/vim-themis/bin/themis

after_success:
  - vint autoload
  - vimlparser autoload/*/*/*.vim > /dev/null
