version: '{build}'
clone_depth: 1

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
before_test:
  - cmd: git clone --depth 1 https://github.com/thinca/vim-themis %TEMP%\vim-themis
  - cmd: git clone --depth 1 https://github.com/thinca/vim-quickrun %TEMP%\vim-quickrun
build: off
test_script:
  - cmd: |
      echo %JAVA_HOME%
      vim --version
      %TEMP%\vim-themis\bin\themis.bat
deploy: off
